apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer  #change according to your environment
    image: myprivate.registry.com/myimage:tag #change according to your environment
  imagePullSecrets:
  - name: myregistrykey #change according to your environment
