apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
  - name: bitnami-redis
    image: public.ecr.aws/bitnami/redis:7.2.4-debian-12-r13
